spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/psr_local
    username: postgres
    password: qwe
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: 'classpath:db/databaseChangeLog.yaml'
application:
  yaml:
